- hosts: "{{ variable_host | default('server') }}"
  tasks:
    - name: Make sure snap installed
      shell: |
        apt remove certbot
        snap install core
        snap refresh core
        snap install --classic certbot
        ln -s -f /snap/bin/certbot /usr/bin/certbot

    - name: Get certs
      shell: |
        certbot --nginx --redirect -n -d chatprompt.pro -d www.chatprompt.pro -m {{ acme_email }} --agree-tos
